name = "pySplitFlap"
version = "1.1.0"
description = "A library for controlling KRONE / MAN split-flap displays"
license = "GPLv3"
author = "Julian Metzler"
author_email = "git@mezgr.de"
requires = ['pyserial']
url = "https://github.com/Mezgrman/pySplitFlap"
keywords = "sign message board library wrapper serial text display train"